spring:
  datasource:
    hikari:
      username: sa
      password: sa
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
  data:
    jpa:
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
